# -*- coding: utf-8 -*-
"""transvision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCvesCvgAwJZqa6GjzAOGf27qNvQ43IJ

Weather Temperature Prediction
│
├── Dataset
│   └── weatherHistory.csv
│
├── Data Cleaning
│   ├── Missing values
│   └── Duplicate removal
│
├── Feature Engineering
│   ├── Hour
│   ├── Day
│   ├── Month
│   ├── Year
│   ├── DayOfWeek
│   ├── Cyclic features
│   ├── Lag features
│   ├── Rolling mean
│   └── Interaction features
│
├── Machine Learning
│   └── Random Forest Regressor
│
├── Evaluation
│   ├── R²
│   ├── MAE
│   └── RMSE
│
├── Forecast
│   └── Temperature prediction
│
└── SQL
    ├── temperature_forecasts
    └── model_metrics

#importing modules
"""

pip install pandas numpy scikit-learn sqlalchemy pymysql matplotlib

import pandas as pd
import numpy as np
import sqlite3

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)

import warnings
warnings.filterwarnings("ignore")

"""#uploadinding dataset"""

from google.colab import files

uploaded = files.upload()

"""#load dataset"""

df = pd.read_csv("weatherHistory.csv")

"""#checking details of dataset"""

print("Dataset Shape:")
print(df.shape)

print("\nFirst 5 rows:")
display(df.head())

print(df.columns.tolist())

"""# Step 6 — Basic dataset information"""

print("Dataset Information:")
df.info()

"""Check missing values:"""

print("\nMissing Values:")
print(df.isnull().sum())

"""Check duplicates:"""

print("\nDuplicate Rows:")
print(df.duplicated().sum())

"""# Step 7 — Remove duplicate records"""

df = df.drop_duplicates()

print("Shape after removing duplicates:")
print(df.shape)

"""# Step 8 — Convert date column

The Formatted Date column contains the timestamp.
"""

df["Formatted Date"] = pd.to_datetime(
    df["Formatted Date"],
    utc=True
)

"""Sort the data chronologically:"""

df = df.sort_values(
    "Formatted Date"
).reset_index(drop=True)

display(
    df[
        [
            "Formatted Date",
            "Temperature (C)",
            "Humidity"
        ]
    ].head()
)

"""# Step 9 — Exploratory Data Analysis

Check temperature statistics:
"""

print(df["Temperature (C)"].describe())

"""Plot temperature:"""

plt.figure(figsize=(12,5))

plt.plot(
    df["Temperature (C)"].iloc[:2000]
)

plt.title("Temperature Trend")
plt.xlabel("Observation")
plt.ylabel("Temperature (°C)")

plt.show()

"""#Step 10 — Check relationship with important weather variables
---
This is useful for your interview because you can say:

"I performed correlation analysis to understand the relationship between temperature and other weather variables before model development."
"""

weather_columns = [
    "Temperature (C)",
    "Humidity",
    "Wind Speed (km/h)",
    "Visibility (km)",
    "Pressure (millibars)"
]

plt.figure(figsize=(10,7))

sns.heatmap(
    df[weather_columns].corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Weather Feature Correlation")

plt.show()

"""# Step 11 — Handle missing values

First, precipitation type:
"""

df["Precip Type"] = df["Precip Type"].fillna("Unknown")

"""Numerical columns:"""

numeric_columns = [
    "Humidity",
    "Wind Speed (km/h)",
    "Wind Bearing (degrees)",
    "Visibility (km)",
    "Pressure (millibars)"
]

for column in numeric_columns:
    df[column] = df[column].fillna(
        df[column].median()
    )

df = df.dropna(
    subset=["Temperature (C)"]
)

print(df.isnull().sum())

"""#Step 12 — Feature Engineering: Time features

Now we extract information from the date.
"""

df["Hour"] = df["Formatted Date"].dt.hour

df["Day"] = df["Formatted Date"].dt.day

df["Month"] = df["Formatted Date"].dt.month

df["Year"] = df["Formatted Date"].dt.year

df["DayOfWeek"] = df["Formatted Date"].dt.dayofweek

df["DayOfYear"] = df["Formatted Date"].dt.dayofyear

display(
    df[
        [
            "Formatted Date",
            "Hour",
            "Day",
            "Month",
            "Year",
            "DayOfWeek",
            "DayOfYear"
        ]
    ].head()
)

"""#Step 13 — Cyclical feature engineering"""

#Hour

df["Hour_Sin"] = np.sin(
    2 * np.pi * df["Hour"] / 24
)

df["Hour_Cos"] = np.cos(
    2 * np.pi * df["Hour"] / 24
)

#Month
df["Month_Sin"] = np.sin(
    2 * np.pi * df["Month"] / 12
)

df["Month_Cos"] = np.cos(
    2 * np.pi * df["Month"] / 12
)

#Day of week

df["DayOfWeek_Sin"] = np.sin(
    2 * np.pi * df["DayOfWeek"] / 7
)

df["DayOfWeek_Cos"] = np.cos(
    2 * np.pi * df["DayOfWeek"] / 7
)

"""#Step 14 — Lag features

This is particularly important for temperature forecasting.

We use previous temperature values to predict future temperature.

Why 24?

The dataset is hourly, so:

Lag 1  = previous hour
Lag 6  = 6 hours ago
Lag 12 = 12 hours ago
Lag 24 = approximately previous day
"""

df["Temp_Lag_1"] = (
    df["Temperature (C)"].shift(1)
)

df["Temp_Lag_2"] = (
    df["Temperature (C)"].shift(2)
)

df["Temp_Lag_3"] = (
    df["Temperature (C)"].shift(3)
)

df["Temp_Lag_6"] = (
    df["Temperature (C)"].shift(6)
)

df["Temp_Lag_12"] = (
    df["Temperature (C)"].shift(12)
)

df["Temp_Lag_24"] = (
    df["Temperature (C)"].shift(24)
)

"""# Step 15 — Humidity lag features"""

df["Humidity_Lag_1"] = (
    df["Humidity"].shift(1)
)

df["Humidity_Lag_3"] = (
    df["Humidity"].shift(3)
)

df["Humidity_Lag_24"] = (
    df["Humidity"].shift(24)
)

"""#Step 16 — Rolling temperature features"""

df["Temp_Rolling_Mean_3"] = (
    df["Temperature (C)"]
    .shift(1)
    .rolling(3)
    .mean()
)

"""6 hours:"""

df["Temp_Rolling_Mean_6"] = (
    df["Temperature (C)"]
    .shift(1)
    .rolling(6)
    .mean()
)

#12 hours:

df["Temp_Rolling_Mean_12"] = (
    df["Temperature (C)"]
    .shift(1)
    .rolling(12)
    .mean()
)

#24 hours:

df["Temp_Rolling_Mean_24"] = (
    df["Temperature (C)"]
    .shift(1)
    .rolling(24)
    .mean()
)

#Rolling standard deviation:

df["Temp_Rolling_Std_6"] = (
    df["Temperature (C)"]
    .shift(1)
    .rolling(6)
    .std()
)

"""Notice the .shift(1).

That is important because it prevents the current target temperature from leaking into its own features

#Step 17 — Interaction features

Create relationships between variables:
"""

df["Humidity_Temp_Interaction"] = (
    df["Humidity"] *
    df["Temperature (C)"].shift(1)
)

df["Wind_Humidity_Interaction"] = (
    df["Wind Speed (km/h)"] *
    df["Humidity"]
)

"""#Step 18 — Remove rows created by lagging

The first 24 or so rows don't have all the historical values.

"""

df = df.dropna().reset_index(drop=True)

print("Shape after feature engineering:")
print(df.shape)

"""# Step 19 — Select features

"""

features = [

    # Current weather
    "Humidity",
    "Wind Speed (km/h)",
    "Wind Bearing (degrees)",
    "Visibility (km)",
    "Pressure (millibars)",

    # Time
    "Hour",
    "Day",
    "Month",
    "Year",
    "DayOfWeek",
    "DayOfYear",

    # Cyclic
    "Hour_Sin",
    "Hour_Cos",
    "Month_Sin",
    "Month_Cos",
    "DayOfWeek_Sin",
    "DayOfWeek_Cos",

    # Temperature history
    "Temp_Lag_1",
    "Temp_Lag_2",
    "Temp_Lag_3",
    "Temp_Lag_6",
    "Temp_Lag_12",
    "Temp_Lag_24",

    # Humidity history
    "Humidity_Lag_1",
    "Humidity_Lag_3",
    "Humidity_Lag_24",

    # Rolling
    "Temp_Rolling_Mean_3",
    "Temp_Rolling_Mean_6",
    "Temp_Rolling_Mean_12",
    "Temp_Rolling_Mean_24",
    "Temp_Rolling_Std_6",

    # Interaction
    "Humidity_Temp_Interaction",
    "Wind_Humidity_Interaction"
]

target = "Temperature (C)"

"""#Step 20 — Create X and y"""

X = df[features]

y = df[target]

print("X shape:", X.shape)

print("y shape:", y.shape)

"""#Step 21 — Train/test split

Because this is forecasting, don't randomly shuffle the data.
"""

split_index = int(
    len(df) * 0.80
)

X_train = X.iloc[:split_index]

X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]

y_test = y.iloc[split_index:]

print("Training data:", X_train.shape)

print("Testing data:", X_test.shape)

"""#Step 22 — Create Random Forest"""

model = RandomForestRegressor(

    n_estimators=500,

    max_depth=None,

    min_samples_split=2,

    min_samples_leaf=1,

    max_features=0.8,

    random_state=42,

    n_jobs=-1
)

"""#Step 23 — Train Random Forest"""

print("Training model...")

model.fit(
    X_train,
    y_train
)

print("Training completed.")

"""#Step 24 — Predict temperatur"""

y_pred = model.predict(
    X_test
)

print("Prediction completed.")

#View predictions:

results = pd.DataFrame({

    "Actual Temperature": y_test.values,

    "Predicted Temperature": y_pred

})

display(results.head(20))

"""#Step 25 — Calculate evaluation metrics

This is an important cell for your company requirement.
"""

r2 = r2_score(
    y_test,
    y_pred
)

mae = mean_absolute_error(
    y_test,
    y_pred
)

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred
    )
)

print("================================")
print("MODEL EVALUATION")
print("================================")

print(
    f"R² Score       : {r2:.4f}"
)

print(
    f"R² Percentage  : {r2 * 100:.2f}%"
)

print(
    f"MAE            : {mae:.4f} °C"
)

print(
    f"RMSE           : {rmse:.4f} °C"
)

"""#Step 26 — Check the 98% requirement

Do not change the test data just to get 98%.

If you don't achieve 98%, we'll tune the model properly in the next step rather than artificially creating a high score.
"""

if r2 >= 0.98:

    print(
        "\n✓ REQUIREMENT PASSED"
    )

    print(
        "R² is greater than or equal to 98%"
    )

else:

    print(
        "\n✗ REQUIREMENT NOT PASSED"
    )

    print(
        "R² is below 98%"
    )

"""#Step 27 — Actual vs predicted graph"""

plt.figure(figsize=(12, 6))

plt.plot(
    y_test.values[:500],
    label="Actual Temperature"
)

plt.plot(
    y_pred[:500],
    label="Predicted Temperature"
)

plt.xlabel("Observation")

plt.ylabel("Temperature (°C)")

plt.title(
    "Actual vs Predicted Temperature"
)

plt.legend()

plt.show()

"""#Step 28 — Scatter plot

---
The closer the points are to a diagonal line, the better the predictions.
"""

plt.figure(figsize=(8, 6))

plt.scatter(
    y_test,
    y_pred,
    alpha=0.4
)

plt.xlabel(
    "Actual Temperature (°C)"
)

plt.ylabel(
    "Predicted Temperature (°C)"
)

plt.title(
    "Actual vs Predicted Temperature"
)

plt.show()

"""#Step 29 — Feature importance

Random Forest gives us feature importance.
"""

importance_df = pd.DataFrame({

    "Feature": features,

    "Importance": model.feature_importances_

})

importance_df = (
    importance_df
    .sort_values(
        "Importance",
        ascending=False
    )
)

display(
    importance_df.head(20)
)

top_features = importance_df.head(15)

plt.figure(figsize=(10, 7))

plt.barh(
    top_features["Feature"][::-1],
    top_features["Importance"][::-1]
)

plt.xlabel("Importance")

plt.ylabel("Feature")

plt.title(
    "Top 15 Random Forest Features"
)

plt.show()

"""#Step 30 — Create forecast dataframe

Now we'll prepare the data that needs to go into SQL.
"""

forecast_df = pd.DataFrame({

    "forecast_datetime":
        df.iloc[
            split_index:
        ]["Formatted Date"].values,

    "actual_temperature":
        y_test.values,

    "forecasted_temperature":
        y_pred,

    "error":
        y_test.values - y_pred
})

#Add metrics:

forecast_df["r2_score"] = r2

forecast_df["mae"] = mae

forecast_df["rmse"] = rmse

#Check:

display(
    forecast_df.head(10)
)

"""#Step 31 — Save forecast as CSV"""

forecast_df.to_csv(
    "temperature_forecast.csv",
    index=False
)

print(
    "Forecast CSV created successfully."
)

#files.download("temperature_forecast.csv")

"""#Step 32 — Create SQL database

Now we satisfy your SQL requirement.

We'll use SQLite because it works directly in Colab.
"""

import sqlite3

connection = sqlite3.connect(
    "weather_forecast.db"
)

print(
    "SQLite database connected."
)

"""#Step 33 — Push forecast data into SQL"""

forecast_df.to_sql(

    "temperature_forecasts",

    connection,

    if_exists="replace",

    index=False
)

print(
    "Forecast data pushed to SQL successfully."
)

"""#Step 34 — Push model metrics into SQL"""

metrics_df = pd.DataFrame({

    "metric": [
        "R2",
        "MAE",
        "RMSE"
    ],

    "value": [
        r2,
        mae,
        rmse
    ]
})

#Push it:

metrics_df.to_sql(

    "model_metrics",

    connection,

    if_exists="replace",

    index=False
)

print(
    "Model metrics pushed to SQL."
)

"""#Step 35 — Check SQL tables"""

query = """
SELECT *
FROM temperature_forecasts
LIMIT 10
"""

sql_result = pd.read_sql_query(
    query,
    connection
)

display(sql_result)

"""#Step 36 — Query model metrics"""

query = """
SELECT *
FROM model_metrics
"""

metrics_result = pd.read_sql_query(
    query,
    connection
)

display(metrics_result)

"""#Step 37 — Run an actual SQL query
---
This demonstrates that you're actually storing and querying the forecast data using SQL
"""

query = """
SELECT
    forecast_datetime,
    actual_temperature,
    forecasted_temperature
FROM temperature_forecasts
ORDER BY forecasted_temperature DESC
LIMIT 10
"""

result = pd.read_sql_query(
    query,
    connection
)

display(result)

"""#Step 38 — Check database tables"""

query = """
SELECT name
FROM sqlite_master
WHERE type='table'
"""

tables = pd.read_sql_query(
    query,
    connection
)

display(tables)

"""#Step 39 — Close SQL connection"""

connection.close()

print("SQL connection closed.")

"""#Step 40 — Download SQL database"""

# files.download(
#     "weather_forecast.db"
# )

